# ----------------------------------
# Dockerfile building a Docker image
# with a NGINX and wbcontent in it--
# ----------------------------------
# ----By Rishat Mukhtarov-----------
FROM nginx:latest

COPY ./index.html /usr/share/nginx/html
COPY ./*.JPG /usr/share/nginx/html

EXPOSE 80
